<?php

use App\KeyPerfomaceIndicator;
use Illuminate\Database\Seeder;

class KeyPerfomaceIndicatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(KeyPerfomaceIndicator::class, 10)->create();
        $key_perfomance_indicators = [
            [
                'name'=>'percentage_of_loaded_capex_loaded_below',
                'target'=>'100',             
                'strategicObjective_id'=>'1',
                'perspective_id'=>'1',
            ],
            [
                'name'=>'percentage_met_of_commited_capex_below',
                'target'=>'100',                
                'strategicObjective_id'=>'1',
                'perspective_id'=>'1',
            ],
            [
                'name'=>'percentage_of_reciept_capex_below',
                'target'=>'100',                
                'strategicObjective_id'=>'1',
                'perspective_id'=>'1',
            ],
            [
                'name'=>'percentage_of_escaleted_complaints_above',
                'target'=>'20',                
                'strategicObjective_id'=>'2',
                'perspective_id'=>'2',
            ],
            [
                'name'=>'percentage_of_returned_questionaires_above',
                'target'=>'75',                
                'strategicObjective_id'=>'2',
                'perspective_id'=>'2',
            ],
            [
                'name'=>'service_desk_SLA_perfomance',
                'target'=>'98.50',                
                'strategicObjective_id'=>'3',
                'perspective_id'=>'2',
            ],
            [
                'name'=>'service_desk_FCR',
                'target'=>'75',              
                'strategicObjective_id'=>'3',
                'perspective_id'=>'2',
            ],
                [
                    'name'=>'Average_Dropped_Call_Ratio_Below',
                    'target'=>'0.30',                    
                    'strategicObjective_id'=>'4',
                    'perspective_id'=>'2',
                ],
            [
                    'name'=>'Avearge_call_setup_success_above',
                    'target'=>'99.40',                   
                    'strategicObjective_id'=>'4',
                    'perspective_id'=>'2',
            ],
            [
                'name'=>'Average_Cell_Availability_above',
                    'target'=>'99.85',                    
                    'strategicObjective_id'=>'4',
                    'perspective_id'=>'2',
            ],
            [
                    'name'=>'Speech_quality_MOS_Above',
                    'target'=>'3.8',                    
                    'strategicObjective_id'=>'4',
                    'perspective_id'=>'2',
            ],
            [
               	    'name'=>'Call_Setup_time_M-M_below',
                    'target'=>'4.5',                    
                    'strategicObjective_id'=>'4',
                    'perspective_id'=>'2',
            ],
            [
                    'name'=>'M-Pesa_TPSs_Count_Below',
                    'target'=>'4.5',                   
                    'strategicObjective_id'=>'5',
                    'perspective_id'=>'2',
            ],
            [
                'name'=>'M-PESA_Availability_above_inPercentage',
                'target'=>'99',
                'strategicObjective_id'=>'5',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'M-PESA_Response_time_above',
                'target'=>'5',
                'strategicObjective_id'=>'5',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'3G_Download_speeds_kbps',
                'target'=>'5000',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'percentage_of_download_speeds_above_3Mbps',
                'target'=>'70',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'3G_upload_speeds_in_kbps',
                'target'=>'1700',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'3G_latency_ms',
                'target'=>'65',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'3G_mean_web_browsing_session_time',
                'target'=>'5.00',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'4G_download_speeds_in_Kbps',
                'target'=>'10.0',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'percentage_of_4G_download_connection_above_1mbps',
                'target'=>'92',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'4G_ipload_speeds_in_Kbps_above',
                'target'=>'7.0',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'4G_latency_in_ms_above',
                'target'=>'42',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'4G_mean_browsing_session_below',
                'target'=>'4.2',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'3G_youtube_reproductions_without_inerruption',
                'target'=>'97',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'4G_youtube_reproductions_without_inerruption',
                'target'=>'99',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'percentage_of_3G_download_connections_above_1Mbps',
                'target'=>'90',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'percentage_of_4G_download_connections_above_3Mbps',
                'target'=>'90',
                'strategicObjective_id'=>'6',
                'perspective_id'=>'2'
            ],
            [
                'name'=>'change_success_rate',
                'target'=>'93',
                'strategicObjective_id'=>'7',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'change_related_incidents',
                'target'=>'1.0',
                'strategicObjective_id'=>'7',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'change_roll_back',
                'target'=>'5',
                'strategicObjective_id'=>'7',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'emmergency_changes',
                'target'=>'5',
                'strategicObjective_id'=>'7',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'unauthorised_changes',
                'target'=>'0',
                'strategicObjective_id'=>'7',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'closed_crqs',
                'target'=>'85',
                'strategicObjective_id'=>'7',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'change_rescheduling',
                'target'=>'5',
                'strategicObjective_id'=>'7',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'incidents_escalation_times(DIT)',
                'target'=>'20',
                'strategicObjective_id'=>'8',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'incidents_report_comliance_within_24Hrs_of_service',
                'target'=>'100',
                'strategicObjective_id'=>'8',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'incidence_escalation_DNOC',
                'target'=>'20',
                'strategicObjective_id'=>'8',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'incidence_communication',
                'target'=>'15',
                'strategicObjective_id'=>'8',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'incidence_notification',
                'target'=>'97',
                'strategicObjective_id'=>'8',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'incidence_report_rate',
                'target'=>'35',
                'strategicObjective_id'=>'9',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'problem_resolution_rate',
                'target'=>'10',
                'strategicObjective_id'=>'9',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'problem_workaround_rate',
                'target'=>'95',
                'strategicObjective_id'=>'9',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'average_problem_resolution_on_time_in_days',
                'target'=>'84',
                'strategicObjective_id'=>'9',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'proactive_problem_ticket_rate',
                'target'=>'30',
                'strategicObjective_id'=>'9',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'problem_reopen_rate',
                'target'=>'2.0',
                'strategicObjective_id'=>'9',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'release_success_rate',
                'target'=>'90',
                'strategicObjective_id'=>'10',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'release_resheduel_rate',
                'target'=>'1.0',
                'strategicObjective_id'=>'10',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'release_incident_rate',
                'target'=>'1.0',
                'strategicObjective_id'=>'10',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'known_release_errors_in_production',
                'target'=>'1.0',
                'strategicObjective_id'=>'10',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'release_withdrawal_rate',
                'target'=>'1',
                'strategicObjective_id'=>'10',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'time_to_detect_incidents',
                'target'=>'60',
                'strategicObjective_id'=>'11',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'time_to_close_incidents',
                'target'=>'21',
                'strategicObjective_id'=>'11',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'CPU_Utilisation_UGW',
                'target'=>'70',
                'strategicObjective_id'=>'12',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'CPU_Utilisation_MSS',
                'target'=>'70',
                'strategicObjective_id'=>'12',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'CPU_Utilisation_MGW',
                'target'=>'70',
                'strategicObjective_id'=>'12',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'CPU_Utilisation_SGSN',
                'target'=>'70',
                'strategicObjective_id'=>'12',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'CPU_Utilisation_MLG',
                'target'=>'50',
                'strategicObjective_id'=>'12',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'Memory_Utilisation_UGW',
                'target'=>'70',
                'strategicObjective_id'=>'13',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'Memory_Utilisation_SGSN',
                'target'=>'80',
                'strategicObjective_id'=>'13',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'Memory_Utilisation_MIG',
                'target'=>'50',
                'strategicObjective_id'=>'13',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'License_Utilisation_UGW',
                'target'=>'70',
                'strategicObjective_id'=>'14',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'License_Utilisation_SGSN',
                'target'=>'70',
                'strategicObjective_id'=>'14',
                'perspective_id'=>'3'
            ],
            [
                'name'=>'No_Champions_trained',
                'target'=>'0.0',
                'strategicObjective_id'=>'15',
                'perspective_id'=>'4'
            ],
            [
                'name'=>'percentage_ITIL_foundation_comletion',
                'target'=>'90',
                'strategicObjective_id'=>'15',
                'perspective_id'=>'4'
            ],
            [
                'name'=>'Awareness_Attendance',
                'target'=>'90',
                'strategicObjective_id'=>'15',
                'perspective_id'=>'4'
            ],
            [
                'name'=>'Ensure annual review of the Quality management system- Management Review',
                'target'=>'4',
                'strategicObjective_id'=>'16',
                'perspective_id'=>'5',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure there are no repeat non-conformities identified during external audit',
                'target'=>'0',
                'strategicObjective_id'=>'16',
                'perspective_id'=>'5',
                'arithmeticStructure'=>'0'
            ], 
            [
                'name'=>'Ensure there are no repeat non-conformities identified during internal audit',
                'target'=>'0',
                'strategicObjective_id'=>'16',
                'perspective_id'=>'5',
                'arithmeticStructure'=>'0'
            ], 
            [
                'name'=>'Number of Internal Audits carried out annually',
                'target'=>'2',
                'strategicObjective_id'=>'16',
                'perspective_id'=>'5',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'One Risk Assessment unertaken on key processes across the business',
                'target'=>'1',
                'strategicObjective_id'=>'17',
                'perspective_id'=>'5',
                'arithmeticStructure'=>'1'
            ],
        
        [
            'name'=>'Ensure annual QMS Awareness',
            'target'=>'80',
            'strategicObjective_id'=>'18',
            'perspective_id'=>'6',
            'arithmeticStructure'=>'1'
        ],
            [
                'name'=>'Increase QMS competencies through Training and awareness',
                'target'=>'90',
                'strategicObjective_id'=>'19',
                'perspective_id'=>'6',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'EBU NPS Details Improve Net Promoter Score (NPS) in relation to Customer Products and Services. Customer Satisfaction',
                'target'=>'40',
                'strategicObjective_id'=>'20',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Customer NPS Details Improve Net Promoter Score (NPS) in relation to Customer Products and Services. Customer Satisfaction',
                'target'=>'61',
                'strategicObjective_id'=>'21',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'0'
            ],
            [
                'name'=>'Ensure Induction for all New Joiners at entry point',
                'target'=>'100',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of que Management(HVC) Hustler section',
                'target'=>'85',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of que Management(HVC) DP section',
                'target'=>'85',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of que Management(HVC) Post Pay section',
                'target'=>'85',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of que Management(HVC) Enterprise section',
                'target'=>'85',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of que Management (YOUTH)',
                'target'=>'80',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of que Management (MASS)',
                'target'=>'80',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of Repeat caller FCR(First Contact Resolution)',
                'target'=>'75',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of  Offered Calls',
                'target'=>'123543',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of answered Calls',
                'target'=>'117366',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Ensure Customer Quality Management in terms of abandoned calls',
                'target'=>'23',
                'strategicObjective_id'=>'22',
                'perspective_id'=>'7',
                'arithmeticStructure'=>'0'
            ],
            //!  ISMS KEY PERFOMANCE INDICATORS.
            [
                'name'=>'Cumulative fraud information security incidents leading to financial loss( impact of 4 to 5)',
                'target'=>'3',
                'strategicObjective_id'=>'25',
                'perspective_id'=>'9',
                'arithmeticStructure'=>'3'
            ],
            [
                'name'=>'Successful ISO 27001 external audit (not more than 1 minor) BSI',
                'target'=>'1',
                'strategicObjective_id'=>'26',
                'perspective_id'=>'9',
                'arithmeticStructure'=>'4'
            ],
            [
                'name'=>'Number of high risk issues raised by External audit on access management',
                'target'=>'0',
                'strategicObjective_id'=>'26',
                'perspective_id'=>'9',
                'arithmeticStructure'=>'5'
            ],
            [
                'name'=>'Percentage of unauthorized or incorrect changes that have led to service downtimes services of customer facing services',
                'target'=>'1.0',
                'strategicObjective_id'=>'27',
                'perspective_id'=>'10',
                'arithmeticStructure'=>'6'
            ],
            [
                'name'=>'Number of incidents related to breached customer information( at a max 4 per week)',
                'target'=>'36',
                'strategicObjective_id'=>'28',
                'perspective_id'=>'10',
                'arithmeticStructure'=>'7'
            ],
            [
                'name'=>'Percentage of active antivirus installed on desktops and laptops',
                'target'=>'95',
                'strategicObjective_id'=>'29',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage of workstations with ISE configuration(NAC)',
                'target'=>'100',
                'strategicObjective_id'=>'29',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage coverage of pentest across Cloud, M-PESA, Mobile Data, Customer Support and Billing',
                'target'=>'100',
                'strategicObjective_id'=>'29',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage coverage of VA(PVMG) across Cloud, M-PESA, Mobile Data, Customer Support and Billing',
                'target'=>'100',
                'strategicObjective_id'=>'29',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage of group 1(Criticality league) systems found without critical vulnerabilties which can lead to direct unauthorized access',
                'target'=>'100',
                'strategicObjective_id'=>'29',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Number of risk assessment cycles carried out during the year',
                'target'=>'2',
                'strategicObjective_id'=>'30',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Number of scheduled 3rd party risk assessments conducted',
                'target'=>'9',
                'strategicObjective_id'=>'30',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Number of management reviews carried out during the year',
                'target'=>'2',
                'strategicObjective_id'=>'30',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage mandatory ISMS documents reviewed',
                'target'=>'100',
                'strategicObjective_id'=>'30',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Number of internal audits carried out annually',
                'target'=>'1',
                'strategicObjective_id'=>'30',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Number of systems in logging scope whose logs are collected centrally across 13 parameters',
                'target'=>'100',
                'strategicObjective_id'=>'31',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage of monthly user access reviews completed by information owners',
                'target'=>'100',
                'strategicObjective_id'=>'32',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage of independent user access reviews per schedule',
                'target'=>'100',
                'strategicObjective_id'=>'32',
                'perspective_id'=>'11',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage of users who resisted phishing attempts',
                'target'=>'90',
                'strategicObjective_id'=>'33',
                'perspective_id'=>'12',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage of all new staff who complete the induction',
                'target'=>'100',
                'strategicObjective_id'=>'33',
                'perspective_id'=>'12',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Percentage of all members of staff who complete the quiz',
                'target'=>'90',
                'strategicObjective_id'=>'33',
                'perspective_id'=>'12',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Number of IRC team members who have completed the ISO 27001 Lead Implementer course',
                'target'=>'80',
                'strategicObjective_id'=>'34',
                'perspective_id'=>'12',
                'arithmeticStructure'=>'1'
            ],
            [
                'name'=>'Number of IRC team members who have completed the Cyber Risk training',
                'target'=>'80',
                'strategicObjective_id'=>'34',
                'perspective_id'=>'12',
                'arithmeticStructure'=>'1'
            ],
            ];

            foreach ($key_perfomance_indicators as $key => $value) {
                KeyPerfomaceIndicator::create($value);
            }
    }
}